# Generated by Django 2.2 on 2023-02-11 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatGPT3_collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatgpt3requestormodel',
            options={'managed': True},
        ),
    ]
